// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiiD8nXrNP19RFzxgF7a-0ZzSUe-dmg1w',
    appId: '1:903641761062:web:de8578c212d776844cade7',
    messagingSenderId: '903641761062',
    projectId: 'project1-6c6fe',
    authDomain: 'project1-6c6fe.firebaseapp.com',
    databaseURL: 'https://project1-6c6fe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project1-6c6fe.appspot.com',
    measurementId: 'G-16Q8VPF0NN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxXNKrqyhjHN1JuEsxTIQHm8CtbTVgjFo',
    appId: '1:903641761062:android:387a9b91f8dec7794cade7',
    messagingSenderId: '903641761062',
    projectId: 'project1-6c6fe',
    databaseURL: 'https://project1-6c6fe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project1-6c6fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5P6rEBVjTbnzLISijLkcvAzIQmi5jthU',
    appId: '1:903641761062:ios:a16e526c2e4c0dac4cade7',
    messagingSenderId: '903641761062',
    projectId: 'project1-6c6fe',
    databaseURL: 'https://project1-6c6fe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project1-6c6fe.appspot.com',
    iosClientId: '903641761062-aolh6de9d724fgn9p2718h0lkqu6eubp.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5P6rEBVjTbnzLISijLkcvAzIQmi5jthU',
    appId: '1:903641761062:ios:cfc2cf57c97d83904cade7',
    messagingSenderId: '903641761062',
    projectId: 'project1-6c6fe',
    databaseURL: 'https://project1-6c6fe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project1-6c6fe.appspot.com',
    iosClientId: '903641761062-ge6mt422q8p985e8gj22ah7066n3uig9.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingApp.RunnerTests',
  );
}
