on:
  push:
    branches: [ "main" ]
    
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
    # Get flutter packages
    - run: flutter pub get
    # Build :D 
    - run: flutter build apk
