name: Dart and Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git /opt/flutter
          export PATH="$PATH:/opt/flutter/bin"
          flutter doctor -v
          flutter --version

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Project
        run: flutter analyze

      - name: Run Tests
        run: flutter test
